### ISSUE TITLE
ubuntu22下运行出错。

### ISSUE THREAD

**Issue by ndcc5** [Cloxl/noss-python#1]
2024-01-10 08:27:03.662 | INFO     | __main__:<module>:268 - 启动进程 46299 并开始挖矿
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/noss-python/main.py", line 177, in mine_data_and_submit
    e_copy = Event(
  File "<string>", line 10, in __init__
  File "/root/noss-python/utils/cuda_envet_id.py", line 73, in __post_init__
    self.compute_id()
  File "/root/noss-python/utils/cuda_envet_id.py", line 101, in compute_id
    self.id = hash_event(envet_str=formatted_event_string)
  File "/root/noss-python/utils/cuda_envet_id.py", line 14, in hash_event
    result = subprocess.run([executable, envet_str, arg2], capture_output=True, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
Traceback (most recent call last):
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/noss-python/main.py", line 177, in mine_data_and_submit
    e_copy = Event(
  File "<string>", line 10, in __init__
  File "/root/noss-python/utils/cuda_envet_id.py", line 73, in __post_init__
    self.compute_id()
  File "/root/noss-python/utils/cuda_envet_id.py", line 101, in compute_id
    self.id = hash_event(envet_str=formatted_event_string)
  File "/root/noss-python/utils/cuda_envet_id.py", line 14, in hash_event
    result = subprocess.run([executable, envet_str, arg2], capture_output=True, text=True)
FileNotFoundError: [Errno 2] No such file or directory: '.\\hash.exe'
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '.\\hash.exe'
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/noss-python/main.py", line 177, in mine_data_and_submit
    e_copy = Event(
  File "<string>", line 10, in __init__
  File "/root/noss-python/utils/cuda_envet_id.py", line 73, in __post_init__
    self.compute_id()
  File "/root/noss-python/utils/cuda_envet_id.py", line 101, in compute_id
    self.id = hash_event(envet_str=formatted_event_string)
  File "/root/noss-python/utils/cuda_envet_id.py", line 14, in hash_event
    result = subprocess.run([executable, envet_str, arg2], capture_output=True, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '.\\hash.exe'
2024-01-10 08:27:04.321 | INFO     | __main__:on_open:26 - 连接中继服务器中...

**Comment by Cloxl** [comment]
dev适配了linux ubuntu在main分支未适配linux系统

你可以自己编译一个hash程序 cuda c++代码在linux重新编译一下就能运行了
